"""empty message

Revision ID: 10603b4f8208
Revises: 1f8f73f6fff0
Create Date: 2019-12-25 11:18:55.339593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10603b4f8208'
down_revision = '1f8f73f6fff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weibo', 'updated')
    # ### end Alembic commands ###
