"""empty message

Revision ID: 6331dff07f45
Revises: 76e61ea45082
Create Date: 2019-12-26 11:29:28.068385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6331dff07f45'
down_revision = '76e61ea45082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('rid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'rid')
    # ### end Alembic commands ###
