"""empty message

Revision ID: 89f1bb8ffda9
Revises: 55a1ce196ed2
Create Date: 2019-12-27 11:15:30.298559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f1bb8ffda9'
down_revision = '55a1ce196ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('n_like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weibo', 'n_like')
    # ### end Alembic commands ###
